name: WakaTime Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          COMMIT_MESSAGE: Update Wakapi stats
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_30_days
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          BLOCKS: "⬜🟨🟩"
